version: 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/expense-manager 

    docker:
      - image: circleci/openjdk:11-jdk
      
    branches:
      only:
        - release
      
    environment:
      JVM_OPTS: -Xmx3200m

    steps:

      - checkout 

      - restore_cache: 
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      
      - run: mvn dependency:go-offline 
      
      - save_cache: 
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      - run: mvn test 
